### ISSUE TITLE
Sector and Industry Grouping

### ISSUE THREAD

**Issue by wu-jeffrey** [wu-jeffrey/ece356-project#10]
Group by Sector and Industry

- (filter by sector / industry) on the companies page

**Comment by eunseochoi** [comment]
`SELECT c.*, s.sectorName FROM Companies c 
INNER JOIN Sectors s ON c.sectorID = s.sectorID
WHERE s.sectorName = "Health Care";`

`SELECT c.*, i.name AS IndustryName FROM Companies c 
INNER JOIN Industries i ON i.industryID = c.industryID
WHERE  i.name = "Publishing";`

example
